#!/usr/bin/env python

import argparse
import json
import numpy as np
from PIL import Image

from labelme import utils

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('json_file')
    parser.add_argument('output_png_file')
    args = parser.parse_args()

    json_file = args.json_file

    data = json.load(open(json_file))

    img = utils.img_b64_to_array(data['imageData'])
    lbl, lbl_names = utils.labelme_shapes_to_label(img.shape, data['shapes'])

    lbl = ((lbl > 0) * 255).astype(np.uint8)
    im = Image.fromarray(lbl)
    im.save(args.output_png_file)
    print('mask saved to {}'.format(args.output_png_file))

if __name__ == '__main__':
    main()
